[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"
solc_version = "0.8.27"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
sandverse = "${SANDVERSE_RPC_ENDPOINT}"

[etherscan]
sandverse = { chain_id = 20197, url = "https://explorer.sandverse.oasys.games/api" }
